# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "jtd" = super.buildPythonPackage rec {
    pname = "jtd";
    version = "0.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/ee/ad8b9b899025761abdec2d10a69ae16fe7d3a8f239b23d841fc1e4b80414/jtd-0.1.1.tar.gz";
      sha256 = "1as8ingak165x4lhbfv90xi75vnsxxsyilpf9kki8k340rwbkaqj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."strict-rfc3339"
    ];
  };
  "strict-rfc3339" = super.buildPythonPackage rec {
    pname = "strict-rfc3339";
    version = "0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
