stuff: '0.1.0'
scope: suchmann
name: bookmarks

generate-typedefs:
  args: --python-out src/typedefs

validate: python3 "$STUFF_REPO_DIR/src/validate.py"
test: python3 "$STUFF_REPO_DIR/src/test.py"

morphs:
  mdff: # markdown from firefox extension with added category headlines
    #load: python3 "$STUFF_REPO_DIR/src/morph-load-mdff.py" # not implemented yet
    save: python3 "$STUFF_REPO_DIR/src/morph-save-mdff.py"

views:
  html:
    load: solara run --port $(python3 "$FLAKE_ROOT/make-port.py" "suchmann.bookmarks.views.html:$STUFF_SOURCE_DIR") "$STUFF_REPO_DIR/src/view-load-html.py"
