stuff: '0.1.0'
scope: suchmann
name: tasksets

generate-typedefs:
  args: --python-out src/typedefs

validate: python3 "$STUFF_REPO_DIR/src/validate.py"
test: python3 "$STUFF_REPO_DIR/src/test.py"

morphs:
  yaml:
    load: python3 "$STUFF_REPO_DIR/src/morph-load-yaml.py"
    save: python3 "$STUFF_REPO_DIR/src/morph-save-yaml.py"

views:
  html:
    load: solara run --port $(python3 "$FLAKE_ROOT/make-port.py" "suchmann.tasksets.views.html:$STUFF_SOURCE_DIR") "$STUFF_REPO_DIR/src/view-load-html.py"
